name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main  # deploy khi push main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # 3️⃣ Install Firebase CLI
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # 4️⃣ Create Service Account file from GitHub Secret
      - name: Setup Firebase Service Account
        run: |
          echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}" > service-account.json
          export GOOGLE_APPLICATION_CREDENTIALS=service-account.json

      # 5️⃣ Authenticate with gcloud
      - name: Authenticate Firebase CLI
        run: gcloud auth activate-service-account ${{ secrets.FIREBASE_CLIENT_EMAIL }} --key-file=service-account.json

      # 6️⃣ Select project
      - name: Select Firebase Project
        run: firebase use king-of-dungeon

      # 7️⃣ Deploy to Firebase Hosting
      - name: Deploy
        run: firebase deploy --only hosting
